### ISSUE TITLE
Output methods ignore the block when the first argument is non-nil

### ISSUE THREAD

**Issue by dgutov** [crohr/syslogger#30]
This is different from the Logger behavior:

```
$ irb --noecho
irb(main):001:0> require 'logger'
irb(main):002:0> l = Logger.new(STDOUT)
irb(main):003:0> l.info("foo") { "bar" }
I, [2015-04-05T01:45:37.844138 #11084]  INFO -- foo: bar
irb(main):004:0> l.error("foo") { "bar" }
E, [2015-04-05T01:49:18.446210 #11084] ERROR -- foo: bar
```

Also see http://ruby-doc.org/stdlib-2.1.0/libdoc/logger/rdoc/Logger.html#method-i-info, especially the first example.

This feature *is* used in the wild: https://github.com/lostisland/faraday/blob/master/lib/faraday/response/logger.rb#L22-L23, and this is an example of a third-party code expecting a Logger value, which I can't simply replace with Syslogger.

**Comment by crohr** [comment]
Thanks for the report. The code at https://github.com/crohr/syslogger/blob/master/lib/syslogger.rb#L55 should be modified to correctly handle this behaviour, i.e. simply delegate to `#add` as done in http://ruby-doc.org/stdlib-2.1.0/libdoc/logger/rdoc/Logger.html#method-i-info. I'll have a go at the end of this week, but if you have time to do it before do not hesitate to send a pull request!

**Comment by dgutov** [comment]
Done, I think. See the pull request.
