### ISSUE TITLE
severity as array in the call to the formatter

### ISSUE THREAD

**Issue by dup2** [crohr/syslogger#35]
The formatter gets called like this on line 96:

```
clean(formatter.call([severity], Time.now, progname, communication))
```

Any reason why the severity is wrapped in an array? The default ruby logger does not use an array here but sends a Severity object which provides a label like "INFO" or "DEBUG" when .to_s is applied.

We are migrating to syslog for all logging in our application and just noted that the call to the formatter is different.

**Comment by n-rodriguez** [comment]
Well here the commit that adds the formatter : https://github.com/crohr/syslogger/commit/e9749cdedee9d99e07eb20065dafd1f73e78affe
Nothing explains why severity is wrapped in an array...
