### ISSUE TITLE
log tags position an availability in the formatter

### ISSUE THREAD

**Issue by dup2** [crohr/syslogger#36]
When using a custom formatter, the log tags are not provided in the message contrary to the tagged logger in rails 3 (4?).

We use a custom formatter implementing `call(severity, time, progname, msg)`.

Using the rails default logger with tagged logging, the `msg` parameter already contains the tags prepended to the actual message. 

When using the Syslogger class, the tags seem to get prepended after the call to the formatter when sending the message to the syslog daemon.

**Comment by n-rodriguez** [comment]
This patch should fix this issue: https://github.com/crohr/syslogger/pull/45
