### ISSUE TITLE
Still maintain?

### ISSUE THREAD

**Issue by n-rodriguez** [crohr/syslogger#40]
Hi! Do you still maintain this gem?

**Comment by carsonreinke** [comment]
@crohr any chance you can add maintainers?  Looks like there is 2 PRs that could be wrapped up quickly.

**Comment by crohr** [comment]
@carsonreinke sure, anyone interested?

**Comment by n-rodriguez** [comment]
@crohr yes :)

**Comment by crohr** [comment]
@n-rodriguez just invited you as collaborator. Feel free to review/merge PRs!

**Comment by crohr** [comment]
(And obviously if you want to merge some of your work from your fork that would be great as well!)

**Comment by carsonreinke** [comment]
@crohr I would like to help close some of the remaining issues.

**Comment by n-rodriguez** [comment]
@crohr thank you!
