### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by n-rodriguez** [crohr/syslogger#43]
Hi! I think we're good for a new release (1.6.5?).
Thank you!

**Comment by thesmart** [comment]
@crohr Hi, any chance we can cut a new release to fix the warning: `vendor/bundle/ruby/2.4.0/gems/syslogger-1.6.4/lib/syslogger.rb:129: warning: constant ::Fixnum is deprecated` ?

**Comment by arturoherrero** [comment]
Same here, can you push a new version of the gem, please?

**Comment by n-rodriguez** [comment]
@crohr the tag for the 1.6.5 release is ready : https://github.com/crohr/syslogger/releases

**Comment by crohr** [comment]
Just pushed 1.6.5, thanks for the work @n-rodriguez

**Comment by n-rodriguez** [comment]
Thank you!
